module.exports = {
  HandGun: {
    name: "HandGun",
    type: "pistol",
    damage: 20,
    distance: 50,
    fireRate: 0.45,
    magazineSize: 12,
    reloadTime: 1.5,
    spread: 0.02,
    recoil: 0.9,
    automatic: false,
  },

  Stinger: {
    name: "Stinger",
    type: "smg",
    damage: 10,
    distance: 75,
    fireRate: 0.1,
    magazineSize: 20,
    reloadTime: 2.0,
    spread: 0.05,
    recoil: 1.3,
    burst: 4,
    automatic: true,
  },

  Claw: {
    name: "Claw",
    type: "shotgun",
    damage: 50,
    pellets: 10,
    distance: 20,
    fireRate: 0.8,
    magazineSize: 2,
    reloadTime: 2.0,
    spread: 0.2,
    recoil: 1.8,
    automatic: false,
  },

  HandVulcan: {
    name: "HandVulcan",
    type: "smg",
    damage: 10,
    distance: 60,
    fireRate: 0.09,
    magazineSize: 25,
    reloadTime: 2.1,
    spread: 0.05,
    recoil: 1.2,
    automatic: true,
  },

  Ironfang: {
    name: "Ironfang",
    type: "rifle",
    damage: 30,
    distance: 100,
    fireRate: 0.16,
    magazineSize: 24,
    reloadTime: 2.2,
    spread: 0.03,
    recoil: 1.1,
    automatic: true,
  },

  Predator: {
    name: "Predator",
    type: "sniper",
    damage: 150,
    distance: 200,
    fireRate: 1.4,
    magazineSize: 5,
    reloadTime: 3.0,
    spread: 0.005,
    recoil: 2.0,
    automatic: false,
  },

  Executioner: {
    name: "Executioner",
    type: "shotgun",
    damage: 40,
    pellets: 12,
    distance: 25,
    fireRate: 1.1,
    magazineSize: 7,
    reloadTime: 2.4,
    spread: 0.18,
    recoil: 1.6,
    automatic: true,
  },

  Bombard: {
    name: "Bombard",
    type: "launcher",
    damage: 120,
    splashRadius: 6,
    selfDamage: true,
    distance: 90,
    fireRate: 1.8,
    magazineSize: 1,
    reloadTime: 3.5,
    spread: 0.1,
    recoil: 2.5,
    automatic: false,
  },

  Vulcan: {
    name: "Vulcan",
    type: "heavy",
    damage: 5,
    distance: 110,
    fireRate: 0.06,
    magazineSize: 100,
    reloadTime: 5.0,
    spread: 0.07,
    recoil: 2.2,
    automatic: true,
  },

  Nothing: {
    name: "Nothing",
    type: "none",
    damage: 0,
    distance: 0,
    fireRate: 1,
    magazineSize: 0,
    reloadTime: 0,
  },
};
